### ISSUE TITLE
Feature : Is there a possibility to have an x86 binaries for Windows

### ISSUE THREAD

**Issue by DoubleLorD** [Jojatekok/MoneroGui.Net#18]
Hello,
Excuse me if this is disturb, but I'm seeking if it is possible to have a build for x86.
Thank you.

**Comment by Jojatekok** [comment]
Sure! MoneroX in itself is fully compatible with the x86 system architecture, but bitmonerod cannot be run on x86 systems due to RAM size issues. I'll release the x86 bundle as soon as the database is implemented to bitmonerod by the core development team.

**Comment by DoubleLorD** [comment]
Hello,
Thank you so much for this clear answer.
I hope so.
